new Promise

```
const promise = new Promise((resolve, reject) => { // 执行器
  // 异步操作代码...
})
```


Promise 作为一个构造函数，通过 new 操作符可创建一个 promise 实例

该构造函数接收一个函数作为参数，这个函数我们通常称为执行器（executor）函数

执行器函数接收两个参数：这两个参数作为函数可调用并可以传入相应数据，通常我们以resolve和reject进行命名


创建 Promise 类

根据上述示例与描述，现在可以先构造一个初步的 Promise 类

- Promise 具备三种状态：pending、fulfilled（有时候也称为 resolved ）、rejected。
- 构造器内定义 executor，接收实例传过来的执行器函数
- 初始状态为 pending。
- 初始 value （终值）， 它是任何一个合法的 JavaScript 值。
- 初始 reason (拒因) 


```
/ 定义 Promise 的三种状态
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

// 定义 MyPromise 类
class MyPromise { 
  constructor(executor) {
    // 初始状态为 pending
    this.status = PENDING
    
    // 初始 value 与 reason
    this.value = undefined
    this.reason = undefined
  }
}

```

resolve 与 reject

回顾一下调用这两个函数的作用

```
const promise = new Promise((resolve, reject) => {
    // 异步操作代码
  setTimeout(() => {
    const rand = Math.random() * 100
    if (rand >= 50) {
        // 成功时执行
      resolve('success')
    } else {
        // 失败时执行
      reject('error')
    }
  }, 1000)
})


```

resolve函数：将 promise 实例的状态从 pending 变为 fulfilled，在异步操作成功时调用，并将异步操作的结果，作为参数进行传递

reject函数： 将 promise 实例的状态从 pending 变为 rejected，在异步操作失败时调用，并将异步操作报出的错误，作为参数进行传递

MyPromise 类中，我们定义 resolve 函数 和 reject 函数，并在函数体内进行 status、value 或 reason的更新，同时调用 executor 执行器，传入 resolve 和 reject

```
// ...
class MyPromise {
  constructor(executor) {
    this.status = PENDING
    this.value = undefined
    this.reason = undefined
    
    // 定义 resolve
    const resolve = value => {
      // 更新状态
      this.status = FULFILLED
      // 更新 value
      this.value = value
    }
    // 定义 reject
    const reject = reason => {
      // 更新状态
      this.status = REJECTED
      // 更新 reason
      this.reason = reason
    }
    // 调用执行器，将 resolve 与 reject 作为参数传递出去
    executor(resolve, reject)
  }
}
    

```

测试

```javascript
// 通过 MyPromise 生成 p1 实例， 执行 resolve 并传递 success 参数
const p1 = new MyPromise((resolve, reject) => {
  resolve('success')
})
console.log(p1) // MyPromise {status: 'fulfilled', value: 'success', reason: undefined}

// 通过 MyPromise 生成 p2 实例， 执行 reject 并传递 error 参数
const p2 = new MyPromise((resolve, reject) => {
  reject('error')
})
console.log(p2) // MyPromise {status: 'rejected', value: undefined, reason: 'error'}

```

状态不可逆

根据规范可知，Promise 必须处于 pending、fulfilled、rejected 三种状态之一，而状态一旦发生改变，则该状态就是落定了，不可逆的，将来都不再会发生改变

测试此前写的代码

```javascript
const p = new MyPromise((resolve, reject) => {
  // 依次执行 resolve 和 reject
  resolve('success')
  reject('error')
})

console.log(p) // MyPromise {status: 'rejected', value: 'success', reason: 'error'}

```

很显然，状态从 pending 过渡到 fulfilled，再从 fulfilled 过渡到 rejected，同时导致 value 和 reason 都有值，这并不符合我们的规范


状态落定

MyPromise 类中，通过添加判断，实现最终的状态落定，即如果状态发生改变，便永不可逆

```javascript

// ...
class MyPromise {
  constructor(executor) {
    this.status = PENDING
    this.value = undefined
    this.reason = undefined

    const resolve = value => {
      // 添加判断
      if (this.status === PENDING) {
        this.status = FULFILLED
        this.value = value
      }
    }
    const reject = reason => {
      // 添加判断
      if (this.status === PENDING) {
        this.status = REJECTED
        this.reason = reason
      }
    }
    executor(resolve, reject)
  }
}

```

状态已经落定

```javascript
const p = new MyPromise((resolve, reject) => {
  resolve('success')
  reject('error')
})

console.log(p) // MyPromise {status: 'fulfilled', value: 'success', reason: undefined}


```

上面的结果显示，状态改变后，便不会再改变了


抛出异常

除了通过调用 resolve、reject 可以改变状态，执行器内抛出异常，也是可以将pending 状态变为 rejected

执行器（executor）函数内改变状态的几种方式

```javascript
/ 初始状态
new Promise((resolve, reject) => {}) // pending 最初状态

// 执行 resolve
new Promise((resolve, reject) => resolve()) // fulfilled 已成功状态

// 执行 reject
new Promise((resolve, reject) => reject()) // rejected 已失败状态

// 抛出异常
new Promise((resolve, reject) => { throw new Error('error') }) // rejected 已失败状态

```

MyPromise 类中，我们通过 try catch 进行捕获，如果捕获到错误就调用 reject

```

lass MyPromise {
  constructor(executor) {
    // ...
    try {
      executor(resolve, reject)
    } catch (error) {
      reject(error)
    }
  }
}

```

测试

```javascript
const p = new MyPromise((resolve, reject) => {
  throw 'error'
})

console.log(p) // MyPromise {status: 'rejected', value: undefined, reason: 'error'}


```


小结

我们创建了一个初步的 Promise 类，定义了三种状态，并初始化 status、value、reason。定义 resolve 和 reject 更新status、value、reason，并在这两个函数体内添加判断最终落定状态，通过调用执行器（executor）将这两个函数作为参数进行传递。使用 try catch 进行错误的捕获，从而在执行器（executor）函数体内抛出异常时可将 promise 实例状态 变为 rejected

```
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

class MyPromise {
  constructor(executor) {
    this.status = PENDING
    this.value = undefined
    this.reason = undefined

    const resolve = value => {
      if (this.status === PENDING) {
        this.status = FULFILLED
        this.value = value
      }
    }
    const reject = reason => {
      if (this.status === PENDING) {
        this.status = REJECTED
        this.reason = reason
      }
    }
    try {
      executor(resolve, reject)
    } catch (error) {
      reject(error)
    }
  }
}


```